# SPDX-License-Identifier: GPL-3.0-only
from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

from .native_sla import (NODE_CLASS_MAPPINGS as NATIVE_SLA_NODES,
                         NODE_DISPLAY_NAME_MAPPINGS as NATIVE_SLA_NAMES)
NODE_CLASS_MAPPINGS.update(NATIVE_SLA_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(NATIVE_SLA_NAMES)
